### ISSUE TITLE
return [] with decode()

### ISSUE THREAD

**Issue by mohamed3a6ala** [vinkla/hashids#12]
i try to hash string decode as the following  but  the return value is empty array []
Note: encode() work well .

get('/test', function(){
    $hash = Hashids::decode('1LLb3b4ck');
    return  $hash;
});

Any Suggestions ?

**Comment by GrahamCampbell** [comment]
You need `return $hash[0]`.

**Comment by vinkla** [comment]
Thanks for helping out @GrahamCampbell!

**Comment by mohamed3a6ala** [comment]
Thanks for help @GrahamCampbell , but still not working returns an error `Undefined offset: 0`

**Comment by GrahamCampbell** [comment]
Looks like the thing your decoding was empty then.

**Comment by mohamed3a6ala** [comment]
I return the above code
 `get('/test', function(){
$hash = Hashids::decode('1LLb3b4ck');
return $hash;
});`
now decoding empty?

**Comment by GrahamCampbell** [comment]
"hash" is NOT an string, so you can't return it like that

**Comment by GrahamCampbell** [comment]
decoding that MUST give an array
