### ISSUE TITLE
Upgrading question

### ISSUE THREAD

**Issue by GrahamCampbell** [vinkla/hashids#131]
If I upgrade from 2.0.4 to 4.0.0, will all the IDs behave in exactly the same way as before?

I just want to be 1000% sure. I can see the semantics of the tests has not changed, at least.

**Comment by vinkla** [comment]
> If I upgrade from 2.0.4 to 4.0.0, will all the IDs behave in exactly the same way as before?

Yes. 

---

List of changes between `2.0.4` and `4.0.0`: [ivanakimov/hashids.php/compare/2.0.4...4.0.0](https://github.com/ivanakimov/hashids.php/compare/2.0.4...4.0.0)

**Comment by halaei** [comment]
@vinkla It will be great if you add some upgrade guide, or note in readme ragarding this issue. Because I have the same question about upgrading between different versions: are the ids of version 4 compatible with version 1?
Thanks.

**Comment by vinkla** [comment]
List of changes between `1.0.0` and `4.0.0`: [ivanakimov/hashids.php/compare/1.0.0...4.0.0](https://github.com/ivanakimov/hashids.php/compare/1.0.0...4.0.0)
