### ISSUE TITLE
wiill a same number get the same result for different salts?

### ISSUE THREAD

**Issue by videni** [vinkla/hashids#135]
> As long as you don't change constructor arguments midway, the generated output will stay unique to your salt

does this  mean a same number might get the same result for different salts?

**Comment by vinkla** [comment]
Not as long as you don't change constructor arguments midway, the generated output will stay unique to your salt.

**Comment by barnabaskecskes** [comment]
@vinkla @videni I've just encountered an exception for that when using very long salts. It is probably not a bug just something to keep an eye out for...

![Screenshot 2020-02-27 at 14 19 10](https://user-images.githubusercontent.com/3535449/75453900-802d1680-596c-11ea-8729-4e7c0fe16e58.png)

> Context: I'm using this package to obscure resource IDs in some systems, constructing the hash dynamically as `"{$fullyQualifiedResourceClassName}::{$saltFromConfig}"` and just stumbled upon this in a larger app where there is a fairly deep folder structure.
