### ISSUE TITLE
About unique article urls

### ISSUE THREAD

**Issue by darkcavalry** [vinkla/hashids#139]
Hello,

I have a article database, Im using hashids for creating unique kesys to call article page like youtube.

Im just using created article autoincrement for hash like;

```
$hashids = new Hashids\Hashids('',12,'0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_');
$key = $hashids->encode(1);
```

and calling article page like that;

`http://www.example.com/wy7aaQHEagZY`

key column is utf8-bin

My question is; 

Should I add another url path for unique depth like http://url/user_name/key ? or this method enough for large amount articles?

Regards.

**Comment by vinkla** [comment]
> key column is utf8-bin

I would suggest to not put hashids in the database. Use autoincrement ids instead and convert the ids to hashids on the fly.

> Should I add another url path for unique depth like http://url/user_name/key ? or this method enough for large amount articles?

It depends on if you want to hide the IDs or not. It's up to you.
