### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by Daaaaad** [vinkla/hashids#14]
Hello,

I get this error when trying to "composer require vinkla/hashids": 

<img width="831" alt="capture d ecran 2015-11-25 a 17 52 49" src="https://cloud.githubusercontent.com/assets/167037/11403496/5de9d3ae-939d-11e5-8f0e-286ca9785868.png">

Can you help ?

Thx,

David.

**Comment by vinkla** [comment]
What other packages do you have installed?

**Comment by Daaaaad** [comment]
Here is the "require" part of my composer.json :

"require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "intervention/image": "^2.3",
        "laravel/socialite": "^2.0",
        "league/flysystem-aws-s3-v3": "^1.0",
        "doctrine/dbal": "^2.5",
        "bugsnag/bugsnag-laravel": "1.*",
        "facebook/php-sdk-v4": "^5.0",
        "barryvdh/laravel-debugbar": "^2.0",
        "pda/pheanstalk": "^3.1",
        "genealabs/laravel-mixpanel": "^0.4.9",
        "algolia/algoliasearch-laravel": "^1.0",
        "exeu/apai-io": "^1.8",
        "uxweb/sweet-alert": "^1.1",
        "hisorange/browser-detect": "^2.0",
        "graham-campbell/manager": "^2.3",
        "vinkla/hashids": "^2.2"
    },

**Comment by GrahamCampbell** [comment]
What about require-dev?

**Comment by Daaaaad** [comment]
"require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1"
    },

**Comment by GrahamCampbell** [comment]
Hmmm.

**Comment by vinkla** [comment]
`algolia/algoliasearch-laravel` uses an older version of the manager.

**Comment by vinkla** [comment]
Nevermind. They don't.

**Comment by vinkla** [comment]
@Daaaaad are you still having problems with this?

**Comment by Daaaaad** [comment]
Yes but I managed to make it work... don't remember how ;)

**Comment by vinkla** [comment]
Great!
