### ISSUE TITLE
Generate integers no strings

### ISSUE THREAD

**Issue by FuriosoJack** [vinkla/hashids#142]
please, Generate integers no strings

**Comment by roukmoute** [comment]
It is not the goal of hashids, read its website: https://hashids.org/
But if you really need it (don't recommended, too big number, risky of duplicates), you can use an [alphabet](https://github.com/vinkla/hashids#using-a-custom-alphabet) and insert only numbers, next just cast into an integer.

**Comment by FuriosoJack** [comment]
> It is not the goal of hashids, read its website: https://hashids.org/
> But if you really need it (don't recommended, too big number, risky of duplicates), you can use an [alphabet](https://github.com/vinkla/hashids#using-a-custom-alphabet) and insert only numbers, next just cast into an integer.

thanks, although what I needed was also to generate from a string a random string of single numbers (not necessarily an integer) and this package only generates string or from two integers (array (41,1)), but if you know any package do that thanks @roukmoute
