### ISSUE TITLE
Collision (different number, same hashid)

### ISSUE THREAD

**Issue by artyuum** [vinkla/hashids#145]
Hi, I'm using Hashids 4 on PHP 7.4.8 and I have the "gmp" extension installed.
Here is a snippet allowing you to reproduce the collision:
```php
<?php

require 'vendor/autoload.php';

use Hashids\Hashids;

$encodedIds = [];

$hashids = new Hashids();

foreach (range(0, 100000) as $number) {
    $encodedId = $hashids->encode($number);
    $collisionIndex = array_search($encodedId, $encodedIds);

    if ($collisionIndex) {
        echo "Collision with:\n";
        echo $collisionIndex  . ' -> ' . $encodedId;

        echo "\n\n";

        echo "For:\n";
        echo $number . ' -> ' . $encodedId;

        die("\n");
    }

    $encodedIds[] = $encodedId;
}

echo 'Done';
```

**Output**
```
Collision with:
587 -> 0E97

For:
25543 -> 0E97
```

**Comment by vinkla** [comment]
587 -> 0E3
25543 -> 0E97

In the future, please submit a pull request with a failing test.

**Comment by artyuum** [comment]
> 587 → 0E3
25543 → 0E97

I don't understand what you said, what is this? Did you execute the snippet above? This is the result?

**Comment by vinkla** [comment]
>This is the result?
Yes.

**Comment by artyuum** [comment]
This is weird, array_search() is supposed to find for duplicate encoded IDs and in your reply above 0E3 != 0E97.
I'll try to open a PR with a failing test.
