### ISSUE TITLE
hrtime hashed id always 12 characters long

### ISSUE THREAD

**Issue by joshbruce** [vinkla/hashids#146]
Hello. My `id`s are all 12 characters long.

Using BC Math.

```php
new HashIds()->encode(hrtime(), 10); // 12 character string

new HashIds()->encode(hrtime(), 24); // 12 character string
```

Happening with or with Salt.

version 4.0

**Comment by vinkla** [comment]
- [Please read the documentation.](https://github.com/vinkla/hashids#use-padding-to-make-your-output-ids-longer)
- `hrtime` returns an array.
- `HashIds` → `Hashids`

**Comment by joshbruce** [comment]
Thanks. I did. Calling `hrtime(true)` which returns a full number, not an array: https://www.php.net/manual/en/function.hrtime.php

[Updated code sample above]

266600371282657 - 15 characters long. I use a pretty complex salt, not sure if that matters (as stated, removing the salt doesn't seem to change things).

Closer to live example:

```php
// $this->time = hrtime(true);
(new Hashids($this->pSalt()))->encode($this->time, 10);

(new Hashids($this->tSalt()))->encode($this->time, 24);
```

I get two different hashes - both are 12 characters long. Please reopen (or should I post a new issue)?

Thank you.

**Comment by vinkla** [comment]
If you think you've found a bug, please submit a pull request with a failing test.

**Comment by joshbruce** [comment]
#149 - done.
