### ISSUE TITLE
mb_convert_encoding(): Illegal character encoding specified

### ISSUE THREAD

**Issue by shanezhiu** [vinkla/hashids#154]
## ENV
+ os: Debian Buster 
+ library version:4.0

## code snippet

```
 $salt = random_bytes(mt_rand(6, 11));
 $inneralCoding = \mb_detect_encoding($salt);
 $hashIds = new Hashids($salt);
```

## question

When` $inneralCoding ` is `false`, a new instance `Hashids` will be failed.

is there neccessary to ensure the salt is UTF-8 encoding?

**Comment by vinkla** [comment]
Thanks for your suggestion but we currently don't have any plans to not ensure UTF-8 encoding.
