### ISSUE TITLE
Same hash for different ids

### ISSUE THREAD

**Issue by geodeveloper** [vinkla/hashids#155]
Hi,

Is there a reason why I'm getting same hash for different numbers?

```php
$hashids = new Hashids\Hashids('', 6);

$hash = $hashids->encode(7992);  // bmOqpe
$hash = $hashids->encode(7904); // bmOQpe
```

The only difference is that they are case-insensitive. Is this how it's supposed to work?

Thanks.

**Comment by vinkla** [comment]
> The only difference is that they are case-insensitive. Is this how it's supposed to work?

Yes.

**Comment by geodeveloper** [comment]
Alright, thanks. I suppose I need to use a lowercase alphabet in this case.
