### ISSUE TITLE
Why isn't there "fluent setters" ?

### ISSUE THREAD

**Issue by Mina-R-Meshriky** [vinkla/hashids#158]
I would first like to thank you for this wonderful library. 

I noticed that if I needed to change the salt or the minHashLength of the class I'll have to make a new object `new Hashids('asd',3);`,
It would be nice to have the ability to change that on the same object.

**Comment by vinkla** [comment]
Thanks for the suggestion. Not sure how this would work and I'm currently not seeing this as a future feature for this library.
