### ISSUE TITLE
encode_hex nt working in PHP

### ISSUE THREAD

**Issue by NamarsahaM** [vinkla/hashids#159]
It returns blank when I use:

````
$hashids = new Hashids\Hashids();
$hashed_text = $hashids->encode_hex("63706b64");

echo $hashed_text;
````

But it gets hashed when I try:-

````
$hashids = new Hashids\Hashids();
$hashed_text = $hashids->encode_hex("63706b");

echo $hashed_text;
````

**Comment by vinkla** [comment]
Thanks for reporting! Please provide a failing test case in a pull request.

**Comment by NamarsahaM** [comment]
I have raised same on stackoverflow:- https://stackoverflow.com/questions/65966294/hashid-encryption-returning-no-value-in-php
