### ISSUE TITLE
Some questions about this lib.

### ISSUE THREAD

**Issue by thiagomoraesp** [vinkla/hashids#162]
Hi guys, i have some questions about this lib, i want do generate some HashIds based on the database ID(that is unique), with this premise i have the following questions:

The hashid would be unique too? There's no chance of a 1 and a 9897 give me the same hashid in some moment?
The hashid is case sensitive?
The default hashid always has the same lenght?
Whats the longe integer id that i can hash with hashid?

Thanks :)

**Comment by miquelfire** [comment]
1 and 2 are yes

Not sure what you're asking about with 3

For 4, with the requirement of one of bcmath or gmp, in theory there is no limit. The actual limit is based on how fast your CPU is, and how much time you want the PHP script taking up to calculate the hash. At least with gmp, less than 64 is native speeds, and for either of the two extensions, I assume you won't notice a CPU hit until around 256-bit (I'm guessing the margin of error with timing how fast the library is cleared at this size)

**Comment by vinkla** [comment]
Thanks for helping out @miquelfire! ⭐

**Comment by thiagomoraesp** [comment]
Thhanks @miquelfire, i have another question, with the dictionary:
ABCDEFGHIJKLMNOPQRTSUVXZYK1234567890

I will have 73815 possible combinations, so how can the hashids keep the id unique when i have more than 73815 ids in my database?
