### ISSUE TITLE
not working inside foreach 

### ISSUE THREAD

**Issue by diadal** [vinkla/hashids#164]
encode  ` Hashids::encode($v);` not working inside foreach for worked outside laravel 8

**Comment by diadal** [comment]
i guess this is the issue 

We've had several requests to add this feature — "it seems so easy to add". We will not add this feature for security purposes, doing so encourages people to encode sensitive data, like passwords. This is the wrong tool for that.

**Comment by diadal** [comment]
my string has - but is ok

**Comment by vinkla** [comment]
Please provide a failing test case in the `HashidsTest` test class in a pull request.
