### ISSUE TITLE
Laravel 9 has been released.  Would be awesome if we could add support to this package 🚀

### ISSUE THREAD

**Issue by Purek** [vinkla/hashids#175]
Laravel 9 has been released.

Would be awesome if we could add support to this package 🚀
Now the error is reported as follows:
 Problem 1
    - illuminate/contracts[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.0.14) does not satisfy that requirement.
    - Only one of these can be installed: illuminate/contracts[dev-master, v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev], laravel/framework[v9.0.0-beta.1, ..., 9.x-dev]. laravel/framework replaces illuminate/contracts and thus cannot coexist with it.
    - vinkla/hashids 9.1.0 requires illuminate/contracts ^8.0 -> satisfiable by illuminate/contracts[v8.0.0, ..., 8.x-dev].

**Comment by vinkla** [comment]
Laravel 9 is supported.
