### ISSUE TITLE
Ability to encode fractions/decimal places 

### ISSUE THREAD

**Issue by ajgaunt** [vinkla/hashids#176]
I understand about not encoding negative numbers, but we have the need to encode numbers containing decimal points. Is this something that may be able to be implemented?

**Comment by SmuSmu** [comment]
How about

Convert to String
Explode to Array with the Point as separator
Pass to hashids

Just as an Idea

**Comment by vinkla** [comment]
> I understand about not encoding negative numbers, but we have the need to encode numbers containing decimal points. Is this something that may be able to be implemented?

Nothing we're planning at the moment.
