### ISSUE TITLE
[PHP 8.1] Deprecated: Implicit conversion from float-string to int loses precision

### ISSUE THREAD

**Issue by xKZL** [vinkla/hashids#179]
Hello, 

I have a deprecation message from PHP 8.1 : 
`Deprecated: Implicit conversion from float-string "5914747797311690437275720" to int loses precision`

It appears in case the hashids cannot be decoded. In my case, I used a message that is NOT a hashids (I haven't found a way to check this is a valid hashid but trying to decode it..)
`$encodedMsg = "af8ccd15-f9a9-406a-a48d-9dcc3950df06";`

Sorry I am not so familiar with hashids, but I can surely help.

**Comment by vinkla** [comment]
Hmm, I'm not sure this is in the scope of the package. Let us know if you find a way to validate your ids.
