### ISSUE TITLE
Wierd problem after using Hashids

### ISSUE THREAD

**Issue by mane-cro** [vinkla/hashids#18]
Hello.
I have i would say weird problem. I will say i am starter in Laravel, but i still find it weird. 
I made some testing CRUD app in Laravel, and everything worked, now i installed Hashids, i set up config file and made encryption of my database id  normally Hashids::encode($client->id) and that works. Then in Clients controller i did like this 
   
    public function edit($id)  {
      $client = Client::findOrFail(Hashids::decode($id));

      return view('client.edit')
      ->with('client', $client);
    }

when i do this, i went to client.blade.php  and i made simple test

     {{$client->name}}

and it throws error   

      Undefined property: Illuminate\Database\Eloquent\Collection::$name

but when i do 

   {{$client}}  

it gives correct data in json format.

When i make normal link to edit page with plain ID (no encoding), remove decode in controller - everything works. What can be the problem. ?   {{$client->name}} is correct 100% since it works as i say without encoding/decoding id

Thanks

**Comment by vinkla** [comment]
Try `Hashids::decode($id)[0]` instead. The `decode()` method returns an array.

**Comment by mane-cro** [comment]
I feel like an idiot -.- Thank you very much!

**Comment by vinkla** [comment]
No worries, this is quite common. The [decode](https://github.com/ivanakimov/hashids.php/blob/master/lib/Hashids/Hashids.php#L145) method doesn't have any docblocs.
