### ISSUE TITLE
Argument 1 passed to Vinkla\Hashids\HashidsServiceProvider::registerFactory() must be an instance of Illuminate\Contracts\Foundation\Application

### ISSUE THREAD

**Issue by martinssipenko** [vinkla/hashids#19]
`Argument 1 passed to Vinkla\Hashids\HashidsServiceProvider::registerFactory() must be an instance of Illuminate\Contracts\Foundation\Application`

Since this commit Lumen Application (now version 5.2) does not implement the contract required anymore.

https://github.com/laravel/lumen-framework/commit/365898c7ddbf48e04f206834c06c85c6bb51a5a5#diff-c9248b3167fc44af085b81db2e292837L36

**Comment by martinssipenko** [comment]
Just noticed that this is a duplicate of already closed issue, although it's not resolved yet.

**Comment by vinkla** [comment]
Fixed in 2.2.1
