### ISSUE TITLE
Error  Invalid text representation (hashids not decoding) with route in plural

### ISSUE THREAD

**Issue by bashman** [vinkla/hashids#192]
Hi. 

I got this error in a table

```
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type bigint: "WB3QyWpXnjKYkN5V4gl1G7RoL798exAvEwPzbLa0ZM6OqJ2mrX"
 (Connection: pgsql, SQL: select * from "citizenships" where "id" = WB3QyWpXnjKYkN5V4gl1G7RoL798exAvEwPzbLa0ZM6OqJ2mrX limit 1)
```

The configuration:

```
config/hashids.php

        \App\Models\Citizenship::class => [
            'salt' => 'safawe',
            'length' => 50,
            'alphabet' => 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890'
        ],
```
![DeepinScreenshot_Seleccionar área_20230315142946](https://user-images.githubusercontent.com/1690516/225408044-a8537331-133c-4ec0-ad83-7c6710adef18.png)

``` 
   app/Providers/RouteServiceProvider.php

        Route::bind('citizenships', function ($value, $route) { // not work in plural
            return $this->getModel(\App\Models\Citizenship::class, $value);
        });
```
![DeepinScreenshot_Seleccionar área_20230315143301](https://user-images.githubusercontent.com/1690516/225408675-453f027f-9d2a-47aa-8e3d-77d9d033641d.png)

Routes in plural:
![DeepinScreenshot_Seleccionar área_20230315143558](https://user-images.githubusercontent.com/1690516/225409380-07d260a4-af2d-4362-950a-0cd6c0332d1c.png)

```
The model:

namespace App\Models;
use App\Traits\Hashidable;
use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Citizenship extends Model
{
    use Hashidable;
    use HasFactory;
    use Searchable;

    protected $fillable = [];

    protected $searchableFields = ['*'];
```

Currently I have a table for users and it works very well (singular route bind), I also use a table for sessions and there are no problems with the User model. The configurations for Citizenship it is the same as the User model. Now, That's the right behavior, handling routes in sigular, in the RouteServiceprovider??

The user working fine. 
![DeepinScreenshot_Seleccionar área_20230315142519](https://user-images.githubusercontent.com/1690516/225407223-12615a0f-4ffd-4a69-b38f-9df9b4493589.png)

The Citizenship error:

![DeepinScreenshot_Seleccionar área_20230315142546](https://user-images.githubusercontent.com/1690516/225407343-6dca64e9-3a3b-4a63-96e4-51a6f16148d3.png)

**Comment by vinkla** [comment]
Please use a forum such as Laracasts or Discord instead.
