### ISSUE TITLE
Different results for large numbers between 32-bit and 64-bit

### ISSUE THREAD

**Issue by Novynn** [vinkla/hashids#193]
The use of the modulo operator on a string (if a large number on 32-bit) on the following line breaks compatibility:
https://github.com/vinkla/hashids/blob/86e9c242658a973064fa5eae18dbb53237cdd8a5/src/Hashids.php#LL114C16-L114C58

The string will be converted into the PHP_INT_MAX on 32-bit which is 2147483647.

A very much non-ideal backwards-compatible fix is replacing it with:
`$number = min($number, 2147483647) % (mb_ord($last, 'UTF-8') + $i);`

**Comment by vinkla** [comment]
Thanks for reporting. Please submit a failing test case and a fix in a pull request.
