### ISSUE TITLE
gmp_mod Argument #1 ($num1) is not an integer string

### ISSUE THREAD

**Issue by sts-ryan-holton** [vinkla/hashids#201]
I'm using the latest version of Hashids in my Laravel 11 project running PHP 8.3 and have stumbled upon an issue, given the following, which is a numeric string:

```php
(new Hashids('', 7))->encode('09009956789098')
```

An error is produced:

> gmp_mod(): Argument #1 ($num1) is not an integer string

I have GMP installed via PHP on the server. What are the workarounds for this please?

**Comment by vinkla** [comment]
Please use a forum instead.

**Comment by sts-ryan-holton** [comment]
Posted at https://stackoverflow.com/questions/78371967/gmp-mod-argument-1-num1-is-not-an-integer-string-hashids-package

**Comment by sts-ryan-holton** [comment]
@vinkla What do you suggest? This didn't happen in older versions of Hashids. If my string doesn't start with a zero then there's no issue.
