### ISSUE TITLE
Same result for different numbers

### ISSUE THREAD

**Issue by anstapol** [vinkla/hashids#202]
Hi there, I'm using the library on a Laravel project to generate a string counterpart of the model unique identifier (integer). 

I successfully used it on one model but now having conflicts with another one as you can see on the screenshot.

Am I missing something?

![Screenshot 2024-06-26 at 08 37 46](https://github.com/vinkla/hashids/assets/33395021/cbfc2087-de95-41e0-992e-356bb52e616e)

**Comment by vinkla** [comment]
This is not the same result. K and k are different characters.

**Comment by anstapol** [comment]
omg, so stupid of me I'm sorry. Had it saving to the MySQL database which is not considering the casing for the unique constraint 🤦‍♂️ 

thank you @vinkla!

btw I've noticed that in the docs the recommended PHP library is https://github.com/sqids/sqids-php is that repo going to eventually replace this one?

**Comment by vinkla** [comment]
> omg, so stupid of me I'm sorry. Had it saving to the MySQL database which is not considering the casing for the unique constraint 🤦‍♂️

Don't recommend saving the hashed IDs in the database.

> btw I've noticed that in the docs the recommended PHP library is https://github.com/sqids/sqids-php is that repo going to eventually replace this one?

Sqids is a successor but Hashids isn't going anywhere.

**Comment by anstapol** [comment]
> Don't recommend saving the hashed IDs in the database.

why not?

**Comment by miquelfire** [comment]
HashIDs (And Sqids) are meant to hide the real number used for the PK. So the database will have a number ID (1, 40, 200, etc.), but the end user will see the results of encoding to HashIDs in the URL, for example.
