### ISSUE TITLE
Raise Exception if match not found

### ISSUE THREAD

**Issue by rohitnaidu19** [vinkla/hashids#28]
I use the following code to decode a Hashid:
`$value = Hashids::decode('doyouthinkthatsairyourebreathingnow')[0];`

Now if the Hashid has no matches I Get an error **"Undefined offset: 0"**. It gives an error status code of 500 whereas it should be 404 not found. Shouldn't an exception be thrown if Hashid decode fails? Or am I missing something?

**Comment by GrahamCampbell** [comment]
You should check if it's isset yourself. This is some code from an app for an example:

![image](https://cloud.githubusercontent.com/assets/2829600/15705873/ee169c5c-27e8-11e6-9046-f0938da5575e.png)

**Comment by vinkla** [comment]
You've to check if it exists within the array. This is how Hashids is built.
