### ISSUE TITLE
Returning empty

### ISSUE THREAD

**Issue by limatheus** [vinkla/hashids#32]
Hi,
Following your example, I got a empty return.
Eg: `Hashids::encode(4815162342);  //returns empty`
Couriously `Hashids::encode(481516234);  //returns the hashid`
There is a limit on id length?
Thanks in advance

**Comment by vinkla** [comment]
This shouldn't be a problem. Please share your config.

**Comment by limatheus** [comment]
@vinkla Here is my config.

```'main' => [
            'salt' => config('app.key', ''),
            'length' => 6,
            'alphabet' => ''
        ],
```

**Comment by vinkla** [comment]
Add an alphabet and try again.

**Comment by vinkla** [comment]
```php
 'main' => [
    'salt' => config('app.key', ''),
    'length' => 6,
    'alphabet' => 'alphabet-goes-here'
],
```
