### ISSUE TITLE
Confusing Config

### ISSUE THREAD

**Issue by rjksn** [vinkla/hashids#4]
The config might be better if it was a little more descriptive. I can fill the salt with garbage, I get that but what are the other values supposed to look like. Length? Alphabet? Idk. 

        'main' => [
            'salt'     => 'your-salt-string',
            'length'   => 'your-length-integer',
            'alphabet' => 'your-alphabet-string'
        ],

**Comment by rjksn** [comment]
Even mentioning that it's a minimum length, and leave the characters as blank. Or pre-populate with the defaults in the HashIds. 

    class Hashids … 
	public function __construct( $salt = '', $min_hash_length = 0, $alphabet = '' )

**Comment by vinkla** [comment]
If you don't like the current description what would make you understand it better? Could you please provide a solution of how you would like it to look.

**Comment by rjksn** [comment]
It's just that the defaults are unknown. So, entering in those would be better than what it is. And length isn't very descriptive. The alphabet description is off here. Maybe, even having the default of the function in place would make it more clear.

    'main' => [
        'salt'                   => 'your-salt-string',    // Enter a random set of characters for security purposes.
        'min_length'      => 0,                            // Change this if you require hashes to be of a specific length. 
        'alphabet'          => ''                             // To change the alphabet default enter the characters you wish to use without spaces (ex. abcABC123)
    ],

Maybe:

    'main' => [
         // Enter a random set of characters for security purposes.
        'salt'                   => 'your-salt-string',
         // Change this if you require hashes to be of a specific length.
        'min_length'      => 0,
        // Change the default characters used in the hash                      
        'alphabet'          => 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890'
                             
    ],

**Comment by vinkla** [comment]
Thanks for sharing this solution but I don't agree. This solutions would mean that we have to release new version and all current setups would have to update their configuration files. Since this is a Laravel wrapper of [the official PHP library](http://hashids.org/php) we provide a link to [their documentation](https://github.com/ivanakimov/hashids.php#example-usage). 

I do agree this could be confusing to newcomers but since its a Laravel wrapper I think its fine. 

Thanks anyway!

**Comment by rjksn** [comment]
Just removing your variables would be less problematic. And, existing
setups are only affected if you change the main length. But whatever.

**Comment by canvural** [comment]
I agree with the confusion.

Official library provides default alphabet. But you are overriding it with `your-alphabet-string`

**Comment by vinkla** [comment]
You're free to use whatever alphabet you want. If you want the default one you can just add it back.

**Comment by canvural** [comment]
Yes i know that. But the official package works right out of the box. But with this i have to make extra steps.
