### ISSUE TITLE
vendor:publish doesn't publish the config

### ISSUE THREAD

**Issue by tremby** [vinkla/hashids#6]
I'm using Laravel 5.1. I'm instructed in the readme to run `php artisan vendor:publish`. But when I do so I get "Nothing to publish." and the configuratin file has not been added to my config directory.

**Comment by GrahamCampbell** [comment]
Did you register the service provider?

**Comment by GrahamCampbell** [comment]
Do you already have a config file named `hashids.php`?

**Comment by tremby** [comment]
Yikes. I thought yes and no, in that order, but I just tried resetting to that state and trying again, and it publishes. Maybe I hadn't saved the config/app.php file the first time. Oops! Sorry!

**Comment by GrahamCampbell** [comment]
No worries. :)
